HWKAPM-764 | Percentage sampling
hawkular/hawkular-apm-opentracing-javascript pull request #22
Opened 2016-11-29 17:20 UTC by pavolloffay

https://issues.jboss.org/browse/HWKAPM-764

This should provide the same functionality as this PR https://github.com/hawkular/hawkular-apm/pull/693

2016-11-30 16:47 UTC, pavolloffay commented
@objectiser @karelhala could you please review?

2016-12-01 16:48 UTC, objectiser commented
@pavolloffay LGTM :+1: - be good if @karelhala could comment in general on the js before merging.

2016-12-02 10:45 UTC, pavolloffay commented
@objectiser thanks! I will wait for Karel's feedback.

2016-12-02 12:11 UTC, karelhala requested changes
Looks good, but I'd change switch statement to Object literal and import whole object looks better with `*`.

2016-12-02 12:11 UTC, karelhala commented on lib/APMSpan.js
> +            }
Honestly I don't like switch statements in Javascript, they are both memory demanding, and hard to read. There is much better way to avoid them by using [object literals](https://toddmotto.com/deprecating-the-switch-statement-for-object-literals/), so this whole switch statement can look like this:

```Javascript
if (reportingLevel) {
  const reportingTypes = {
    [REPORTING_LEVEL_NONE]: false, 
    [REPORTING_LEVEL_IGNORE]: false,
    [REPORTING_LEVEL_ALL]: true
  };
  return reportingTypes.hasOwnProperty(reportingLevel) ? reportingTypes[reportingTypes] : true;
}
```

2016-12-02 12:11 UTC, karelhala commented on lib/APMTracer.js
> +import constants from './constants';
Might be better to indicate that you are importing whole object via `*`:
```Javascript
import * as constants from './constants';
```

2016-12-02 12:11 UTC, karelhala commented on lib/sampler.js
> +        return neverSample(trace);
Here I'd prefer assigning function to variable:
```Javascript
class Sampler {
  isSampled(trace) {} // eslint-disable-line no-unused-vars
}

class AlwaysSample extends Sampler {
  constructor() {
    super();
    this.isSampled = alwaysSample;
  }
}

class NeverSample extends Sampler {
  constructor() {
    super();
    this.isSempled = neverSample;
  }
}
```
The benefit of this is you don't have to know what arguments will be used in `isSampled` function and in `neverSample`, `alwaysSample`. But on the other hand, it looks more ugly than returning result of function. So it's up to you what you will choose.

2016-12-02 14:59 UTC, pavolloffay commented on lib/sampler.js
> +        return neverSample(trace);
yes I like this, I used it in `PercentageSampler`

2016-12-02 15:14 UTC, pavolloffay commented on lib/APMSpan.js
> +            }
you have a small typo there:
` return reportingTypes.hasOwnProperty(reportingLevel) ? reportingTypes[reportingLevel] : true;`

Well in some cases it's nicer to use `object literals`. I will stick with switch statement here.

2016-12-02 15:15 UTC, pavolloffay commented
@karelhala  thanks!

2016-12-02 15:22 UTC, merged